spring:
  datasource:
    url: jdbc:mysql://database-blog.c0iymujbsjzh.ap-northeast-1.rds.amazonaws.com:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.wdy.blog: debug
  file:
    name: log/blog-prod.log
server:
  port: 8080